name: CI

on:
  pull_request:
    branches: [ dev, main ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: ["3.8", "3.9", "3.10"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          chmod +x venv.sh
          chmod +x venv_base.sh
          chmod +x venv_django.sh
          chmod +x venv_django_example.sh
          ./venv.sh
      - name: Check Formatting
        run: |
          . venv_base/bin/activate
          chmod +x format_code.sh
          chmod +x check_formatting.sh
          ./check_formatting.sh
      - name: Test Code
        run: |
          . venv_django/bin/activate
          chmod +x django-powertables/run_tests.py
          ./django-powertables/run_tests.py
      - name: Run tox
        run: |
          . venv_django/bin/activate
          tox -e py
